### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by pdeak** [caddyserver/caddy-docker#62] opened 2020-04-11 12:10 UTC
Not sure if this is specific to the docker image. My docker containers automatically update (using ouroboros), and since the last caddy update, I now get an error for every request to caddy. I'm mainly using it as a reverse proxy to a bunch of other sites.

```
2020/04/11 12:05:42 http2: panic serving x.x.x.x:33884: runtime error: invalid memory address or nil pointer dereference
goroutine 117 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc0001281b0, 0xc0008e3f8e, 0xc000256d80)
        net/http/h2_bundle.go:5713 +0x16b
panic(0x144d380, 0x2470800)
        runtime/panic.go:969 +0x166
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc0007d0900, 0x192e1e0, 0xc0001281b0, 0xc00070f800)
        github.com/caddyserver/caddy/v2@v2.0.0-rc.2/modules/caddyhttp/server.go:203 +0x932
net/http.serverHandler.ServeHTTP(0xc0005e0380, 0x192e1e0, 0xc0001281b0, 0xc000244400)
        net/http/server.go:2807 +0xa3
net/http.initALPNRequest.ServeHTTP(0x19335a0, 0xc00065ac90, 0xc000115c00, 0xc0005e0380, 0x192e1e0, 0xc0001281b0, 0xc000244400)
        net/http/server.go:3381 +0x8d
net/http.(*http2serverConn).runHandler(0xc000256d80, 0xc0001281b0, 0xc000244400, 0xc000aa7360)
        net/http/h2_bundle.go:5720 +0x8b
created by net/http.(*http2serverConn).processHeaders
        net/http/h2_bundle.go:5454 +0x4e1
```

I tried deleting the config/data directories and forcing a reset, but the error remains.

**Comment by mholt** [comment] 2020-04-11 14:08
This is already fixed in the latest commits on master (in the caddy repo).

**Comment by francislavoie** [comment] 2020-04-11 14:38
The easiest thing you could do here is to use `caddy/caddy:2.0.0-rc.1`, or alternatively use a volume to replace `/usr/bin/caddy` with the latest build artifact from the master branch: https://github.com/caddyserver/caddy/actions/runs/75592323

For reference, this is a duplicate of https://github.com/caddyserver/caddy/issues/3248

**Closed by francislavoie** 2020-04-11 14:38 UTC
