### ISSUE TITLE
Caddy 2.7.5-builder is missing specific architectures

### ISSUE THREAD

**Issue by douglasparker** [caddyserver/caddy-docker#325] opened 2023-10-12 10:04 UTC
I have new builds of Caddy dockerized automatically with plugins that I want included.

Today my GitHub workflow started failing because there are many architectures missing from `caddy:2.7.5-builder `.

I specifically need linux/amd64.

It might not be a bad idea to automate builds and use ghcr.io so builds are not delayed. See issues #312 and https://github.com/caddyserver/caddy/issues/5732

It seems like with every new Caddy release, caddy-docker has more issues opened because the delay of docker builds causes problems for everyone.

Edit: My workflow checks for new releases every hour. I get an email notification of a failed workflow every hour as well. Almost 8 hours and my inbox just gets spammed. Timely releases is important especially for critical severity CVEs.

The docker guy being on vacation is a problem that should be dealt with via automation.

For Reference:

Caddy 2.7.5:
![image](https://github.com/caddyserver/caddy-docker/assets/18235822/aaece8bf-a3e5-4e5a-81ff-115c8d66fbbd)

Caddy 2.7.4:
![image](https://github.com/caddyserver/caddy-docker/assets/18235822/dddbe3a1-049b-41df-a928-c3b4ffcb4a0f)

**Comment by francislavoie** [comment] 2023-10-12 11:31
Duplicate of https://github.com/caddyserver/caddy-docker/issues/324#issuecomment-1758956763

**Closed by francislavoie** 2023-10-12 11:31 UTC

**Comment by francislavoie** [comment] 2023-10-12 11:32
To be clear, this is entirely out of our control. It's in the build queue. We did everything we could literally as fast as possible for this release. Please have patience.
